# Generated by Django 3.2.16 on 2025-02-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoryTeller', '0002_blogcomment_certification_contactsubmission_newslettersubscriber_project_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='post',
        ),
        migrations.DeleteModel(
            name='ContactSubmission',
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
