# Generated by Django 3.2.16 on 2025-02-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryTeller', '0003_auto_20250219_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newslettersubscriber',
            old_name='date_subscribed',
            new_name='subscribed_at',
        ),
        migrations.AddField(
            model_name='sibling',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
