# Generated by Django 3.2.16 on 2025-02-21 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StoryTeller', '0004_auto_20250219_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_supports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='support',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='support_attachments/'),
        ),
        migrations.AddField(
            model_name='support',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('account', 'Account'), ('billing', 'Billing'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='support',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='support',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=15),
        ),
        migrations.AddField(
            model_name='support',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to=settings.AUTH_USER_MODEL),
        ),
    ]
