# Generated by Django 3.2.16 on 2025-02-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryTeller', '0005_auto_20250221_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contacts/'),
        ),
    ]
