# Generated by Django 3.2.16 on 2025-02-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryTeller', '0006_contact_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='image',
        ),
        migrations.AddField(
            model_name='certification',
            name='certificate_image',
            field=models.FileField(blank=True, null=True, upload_to='certificate_images'),
        ),
    ]
