# Generated by Django 3.2.16 on 2025-03-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryTeller', '0009_auto_20250303_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='due_at',
            field=models.DateField(null=True),
        ),
    ]
