# Generated by Django 3.2.16 on 2025-03-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryTeller', '0010_job_due_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
