# Generated by Django 3.2.16 on 2025-03-04 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoryTeller', '0011_alter_blogpost_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StoryTeller.myuser'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile Development'), ('ai', 'Artificial Intelligence'), ('graphic', 'Graphic Design'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='technology',
            field=models.CharField(help_text='Comma-separated (e.g., Python, Django, React)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='portfolio_videos/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
