# Generated by Django 3.2.16 on 2025-03-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryTeller', '0012_auto_20250304_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='technology',
            field=models.CharField(help_text='Comma-separated (e.g., Python, Django, React)', max_length=2445, null=True),
        ),
    ]
