# Generated by Django 3.2.16 on 2025-03-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryTeller', '0013_alter_portfolioitem_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
